# Generated by Django 5.2.7 on 2025-11-06 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cuotas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_socio", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
                ),
                ("beneficios", models.TextField()),
            ],
            options={
                "db_table": "Cuotas",
            },
        ),
        migrations.CreateModel(
            name="Eventos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField()),
                ("lugar", models.CharField(max_length=100)),
                ("imagen", models.CharField(default="default.png", max_length=100)),
            ],
            options={
                "db_table": "Eventos",
            },
        ),
        migrations.CreateModel(
            name="Merchandising",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=6)),
                ("descripcion", models.TextField()),
                ("imagen", models.CharField(default="default.png", max_length=100)),
                ("imagen2", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "Merchandising",
            },
        ),
        migrations.CreateModel(
            name="Socio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "segundo_apellido",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("mayor13", models.BooleanField(default=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "tipo_socio",
                    models.CharField(
                        choices=[
                            ("menor", "Menor"),
                            ("socio", "Socio"),
                            ("nuevo", "Nuevo"),
                        ],
                        default="nuevo",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                ("telefono", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "Socios",
            },
        ),
        migrations.CreateModel(
            name="Pagos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateField(auto_now_add=True)),
                (
                    "cuota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="appProjectDjango.cuotas",
                    ),
                ),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="appProjectDjango.socio",
                    ),
                ),
            ],
            options={
                "db_table": "Pagos",
            },
        ),
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("mensaje", models.TextField()),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "socio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appProjectDjango.socio",
                    ),
                ),
            ],
            options={
                "db_table": "Contactos",
            },
        ),
        migrations.CreateModel(
            name="AsistenciaEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="appProjectDjango.eventos",
                    ),
                ),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="appProjectDjango.socio",
                    ),
                ),
            ],
            options={
                "db_table": "AsistenciaEvento",
                "unique_together": {("socio", "evento")},
            },
        ),
    ]
