# Generated by Django 5.2.7 on 2025-11-24 12:49

from django.db import migrations
import os
import json

def load_initial_data(apps, schema_editor):
    ruta_json = os.path.join(os.path.dirname(__file__), "..", "..", "copia_bd.json")
    with open(ruta_json, 'r', encoding='utf-8') as f:
        initial_data = json.load(f)

    model_map = {
        "appProjectDjango.socio": apps.get_model("appProjectDjango", "Socio"),
        "appProjectDjango.eventos": apps.get_model("appProjectDjango", "Eventos"),
        "appProjectDjango.cuotas": apps.get_model("appProjectDjango", "Cuotas"),
        "appProjectDjango.merchandising": apps.get_model("appProjectDjango", "Merchandising"),
        "appProjectDjango.pagos": apps.get_model("appProjectDjango", "Pagos"),
        "appProjectDjango.contacto": apps.get_model("appProjectDjango", "Contacto"),
        "appProjectDjango.asistenciaevento": apps.get_model("appProjectDjango", "AsistenciaEvento"),
    }

    for data in initial_data:
        model_key = data["model"]
        if model_key not in model_map:
            continue
            
        Model = model_map[model_key]
        fields = data["fields"]
        # Add PK explicitly
        fields["id"] = data["pk"]
        
        final_fields = {}
        for field_name, value in fields.items():
            # Check if field is a ForeignKey and value is an integer (ID)
            try:
                field = Model._meta.get_field(field_name)
                if field.many_to_one and isinstance(value, int):
                    final_fields[f"{field_name}_id"] = value
                else:
                    final_fields[field_name] = value
            except Exception:
                # If field lookup fails, just pass as is
                final_fields[field_name] = value
                
        Model.objects.create(**final_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("appProjectDjango", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
