# Generated by Django 5.2.7 on 2025-11-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProjectDjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandising',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
