# Generated by Django 5.2.7 on 2025-11-06 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appProjectDjango", "0002_alter_merchandising_precio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cuotas",
            old_name="descripcion",
            new_name="beneficios",
        ),
        migrations.RemoveField(
            model_name="cuotas",
            name="fecha_pago",
        ),
        migrations.RemoveField(
            model_name="cuotas",
            name="monto",
        ),
        migrations.RemoveField(
            model_name="cuotas",
            name="socio",
        ),
        migrations.AddField(
            model_name="cuotas",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="cuotas",
            name="tipo_socio",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="eventos",
            name="imagen",
            field=models.CharField(default="default.png", max_length=100),
        ),
        migrations.AddField(
            model_name="merchandising",
            name="imagen2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="socio",
            name="apellido",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="socio",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socio",
            name="mayor13",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="socio",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="socio",
            name="segundo_apellido",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="socio",
            name="tipo_socio",
            field=models.CharField(
                choices=[("menor", "Menor"), ("socio", "Socio"), ("nuevo", "Nuevo")],
                default="nuevo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="socio",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="socio",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="socio",
            name="telefono",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("mensaje", models.TextField()),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "socio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appProjectDjango.socio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pagos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateField(auto_now_add=True)),
                (
                    "cuota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="appProjectDjango.cuotas",
                    ),
                ),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="appProjectDjango.socio",
                    ),
                ),
            ],
        ),
    ]
