# Generated by Django 5.2.8 on 2025-12-01 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appProjectDjango", "0002_load_intial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asistenciaevento",
            name="fecha_registro",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="contacto",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="contacto",
            name="fecha_envio",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="eventos",
            name="fecha",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="eventos",
            name="nombre",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="merchandising",
            name="nombre",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="pagos",
            name="fecha_pago",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="socio",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="socio",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="socio",
            name="nombre",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="socio",
            name="telefono",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "El teléfono solo puede contener números"
                    )
                ],
            ),
        ),
    ]
