# Generated by Django 5.2.7 on 2025-11-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appProjectDjango", "0003_rename_descripcion_cuotas_beneficios_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contacto",
            table="Contacto",
        ),
        migrations.AlterModelTable(
            name="cuotas",
            table="Cuotas",
        ),
        migrations.AlterModelTable(
            name="eventos",
            table="Eventos",
        ),
        migrations.AlterModelTable(
            name="merchandising",
            table="Merchandising",
        ),
        migrations.AlterModelTable(
            name="pagos",
            table="Pagos",
        ),
        migrations.AlterModelTable(
            name="socio",
            table="Socio",
        ),
    ]
